Repository mirzakhany/django_boilerplate, pull requests merged in 2020-10, with the labels that each got.

#12 OPT: change directory structure
  src/apps/__init__.py
  src/manage.py
  src/proj/__init__.py
  src/proj/asgi.py
  src/proj/settings.py
  src/proj/settings/__init__.py
  src/proj/settings/base.py
  src/proj/settings/build.py
  src/proj/settings/development.py
  src/proj/settings/production.py
  src/proj/settings/staging.py
  src/proj/urls.py
  src/proj/wsgi.py
Labels: hacktoberfest-accepted

#11 docker files and uwsgi script
  deploy/BaseDockerfile
  deploy/Dockerfile
  deploy/entrypoint.sh
  deploy/uwsgi.ini
  entrypoint.sh
  uwsgi.ini
Labels: hacktoberfest-accepted

#13 FIX:change docker file to use src folder
  deploy/Dockerfile
Labels: hacktoberfest-accepted

#14 OPT: change setting structure, add requirements.txt and upgrade docker
  .gitignore
  deploy/BaseDockerfile
  deploy/Dockerfile
  requirements.txt
  src/proj/settings.py
  src/proj/settings/__init__.py
  src/proj/settings/base.py
  src/proj/settings/dev.py
  src/proj/settings/development.py
  src/proj/settings/prod.py
  src/proj/settings/production.py
  src/proj/settings/staging.py
  src/proj/settings/test.py
Labels: hacktoberfest-accepted

#16 NEW: add tox to the project
  .flake8
  .gitignore
  pyproject.toml
  requirements-testing.txt
  src/manage.py
  src/proj/asgi.py
  src/proj/settings/__init__.py
  src/proj/settings/base.py
  src/proj/settings/build.py
  src/proj/settings/dev.py
  src/proj/settings/prod.py
  src/proj/settings/test.py
  src/proj/urls.py
  src/proj/wsgi.py
  tox.ini
Labels: hacktoberfest-accepted

#17 NEW: build scripts
  README.md
  deploy/scripts/build_base_image.sh
  deploy/scripts/build_image.sh
  deploy/scripts/values_sample.sh
Labels: documentation, enhancement

#22 OPT: change requirements structures, Add pip-compile
  README.md
  deploy/BaseDockerfile
  requirements.txt
  requirements/requirements-base.in
  requirements/requirements-base.txt
  requirements/requirements-dev.example.in
  requirements/requirements-dev.in
  requirements/requirements-dev.txt
  requirements/requirements-testing.in
  requirements/requirements-testing.txt
  tox.ini
Labels: enhancement, hacktoberfest-accepted

#23 OPT: Use environ package instead of dotenv
  pyproject.toml
  requirements/requirements-base.in
  requirements/requirements-base.txt
  src/manage.py
  src/proj/settings/base.py
Labels: hacktoberfest-accepted
